from __future__ import annotations

from typing import Any

ALLOWED_TOP_LEVEL = {
    "seed",
    "output_dir",
    "data",
    "model",
    "loss",
    "train",
    "eval",
}

ALLOWED_DATA_KEYS = {
    "train_manifest", "val_manifest", "crop_size", "scale_range",
    "hflip_prob", "brightness_jitter", "contrast_jitter", "gamma_jitter",
    "random_invert_prob", "data_root", "cache_images", "preload",
    "pad_small_images", "max_size", "boundary_margin",
}

ALLOWED_MODEL_KEYS = {
    "output_stride",
    "feature_width",
    "max_trainable_params",
    "backbone",
    "backbone_name",
    "pretrained",
    "backbone_lr_scale",
    "init_m0",
    "neck_type",
    "region_sizes_px",
    "region_overlap",
    "include_full_image",
    "enable_solver",
    "iterations",
    "omega",
    "sirt_omega",
    "residual_clip",
    "dispersion_init",
    "dispersion_min",
    "dispersion_max",
    "reliability_mode",
    "reliability_rate_std_floor",
    "reliability_weight_min",
    "reliability_weight_max",
    "normalize_reliability_within_scale",
    "detach_region_mean_in_solver",
    "detach_reliability_in_solver",
    "uniform_reliability",
    "eps",
    "native_scale_pooling",
    "regional_feature_stats",
    "context_dilations",
    "use_aspp_gap",
    "aspp_dilations",
    "region_head_hidden",
    # RMR-v7
    "hurdle_head",
    "tv_lambda",
    "ema_decay",
    "temp_softplus",
    # RMR-v8 Stage 2
    "solver_mode",
    "density_gate_rho",
    "density_gate_floor",
    "tv_type",
    "tv_eps_c",
    # RMR-v8 Stage 3
    "use_coord_attn",
    # RMR-v9.1 / AQ-RMR additions
    "proximal_tau",
    # RMR-v10 additions
    "proximal_mode",
    "proximal_mu",
    "dynamic_scale_routing",
    "scale_router_temperature",
    # RMR-v11 additions
    "trust_region_kappa",
    "trust_region_floor",
    "trust_region_floor_dense",
    "foreground_gate",
    # RMR-v13 additions
    "adjoint_mode",
    "morozov_gamma",
    # RMR-v14 additions
    "use_top_down_semantic_gate",
    "tdsg_floor",
    "fg_gate_floor",
    # RMR-v15 additions
    "scale_conditioned_prior",
    "pre_solver_scale_gating",
    "scale_gating_power",
    "dynamic_trust_gate",
    "trust_gate_init_bias",
    # RMR-v17 additions
    "density_curvature",
    "use_barzilai_borwein",
    "use_scale_entropy_trust",
    # RMR-v18 additions
    "perspective_scale_bias",
    "perspective_horizon_gate",
    "horizon_cutoff",
    # RMR-v19 additions
    "factorized_scale_routing",
    "num_marginal_scales",
    "num_aspect_ratios",
    "gated_density_curvature",
    "curvature_dense_threshold",
    "curvature_gate_beta",
    "curvature_pool_kernel",
    # RMR-v20 additions
    "use_micro_coord_attn",    # Permanently banned but key must be recognized to raise correct error
    "micro_coord_reduction",   # Permanently banned but key must be recognized to raise correct error
    "use_nesterov_momentum",
    "adaptive_relaxation",
    "adaptive_relax_sparse",
    "adaptive_relax_dense_boost",
    "adaptive_relax_threshold",
    "adaptive_relax_scale",
    # RMR-v21 additions
    "hybrid_recovery_alpha",
    # RMR-v22 additions
    "scale_conditioned_fine_head",
    "density_gated_diffusion",
    "diffusion_dense_threshold",
    "diffusion_gate_beta",
    # RMR-v24 additions
    "use_perspective_elevation",
    "use_alternating_bb",
    # RMR-v26 additions
    "bb_clamp_min",
    "bb_clamp_max",
    # RMR-v27 additions
    "cyclic_bb_length",
    # RMR-v29 additions
    "subpixel_stride2",
    "subpixel_dm",
    # RMR-v30 additions
    "use_anscombe_sirt",
    "anscombe_c",
    "adaptive_tau",
    "adaptive_tau_rho0",
    # RMR-v31 additions
    "anisotropic_diffusion",
    "pm_kappa",
    "density_gated_anscombe",
    "anscombe_tau_dense",
    "area_normalized_adjoint",
    # RMR-v32 additions
    "use_cpcm", "cpcm_hidden", "floor_tau",
    # RMR-v33 additions (H7/H8 Resonant Adjoint, CRCDF, A-SAM)
    "resonant_adjoint", "resonant_adjoint_lambda", "anscombe_morozov",
    "crest_discovery_flux", "crest_kappa_0", "crest_eps_seed",
    "asymmetric_morozov", "morozov_gamma_under", "morozov_rho",
    "curvature_alpha_init",
    # PARK Perspective-Adaptive Regional Kernels & PGH
    "use_park", "park_mode", "park_horizon_h", "park_foreground_h",
    "park_max_aspect", "use_pgh", "park_routing", "park_altitude_bands",
    # DiAG Dynamic Image-Adaptive Geometry (RMR-v34)
    "use_diag", "diag_persp_slope_init",
    "use_vertical_gradient_dcap", "use_dcap_tilt",
    # Sub-60 & Gen 12-15 Mathematical Operators
    "shifted_carrier", "shifted_carrier_eps",
    "density_adaptive_trust", "trust_dense_tau", "trust_dense_kappa",
    "density_scale_gating", "density_scale_tau",
    "hurdle_gating_mode", "asymmetric_trust", "trust_pos_kappa",
    "detach_y0_for_solver",
    "spatial_morozov", "morozov_gamma_scales",
    "scale_routed_trust", "scale_seeded_carrier", "scale_seed_eps",
    "hdc_dilations", "density_adaptive_scale", "density_scale_gamma", "density_scale_learnable",
    "evidence_anchored_trust", "eatr_alpha", "scale_prior_boost",
    "morozov_rho_cap",
    "pad_small_images", "wsd_stable_ratio", "min_lr_ratio", "bayesian_norm_mode",
    "adaptive_sigma", "bayesian_adaptive_sigma", "faithful_dispersion_detach",
    "multiscale_morozov", "morozov_scale_beta",
}

ALLOWED_LOSS_KEYS = {
    "lambda_count", "lambda_count_l1", "lambda_flat_dm16", "lambda_cell",
    "lambda_region_nb", "lambda_hurdle", "lambda_trunc_nb",
    "allocation_loss_type", "bayesian_sigma", "bayesian_background_ratio",
    "ot_reg", "ot_num_iters", "count_loss_mode", "count_nb_dispersion",
    "kappa_flat16", "normalize_flat_dm16", "cell_beta",
    "use_hierarchical_dm", "use_multiscale_dm", "dm_block_sizes_px",
    "dm_weights", "dm_kappas",
    # RMR-v8 Stage 2 & 3
    "cell_loss_mode", "cell_mass_weight_eps", "cell_mass_weight_alpha",
    # RMR-v9: allocation loss target ("y0" | "y")
    "dm_target", "dm_strict",
    # RMR-v11 additions
    "cell_mass_weight_gamma", "lambda_curvature", "lambda_hard_bg", "hard_bg_ratio", "lambda_fg_gate",
    # RMR-v12 additions
    "curvature_gate_threshold", "curvature_gate_kernel", "curvature_gate_mode", "curvature_gate_scale",
    # RMR-v13 additions
    "lambda_scale_align", "scale_align_tau_dense", "scale_align_tau_sparse", "scale_align_kernel",
    # RMR-v14 additions
    "scale_align_mask_bg",
    # RMR-v20 additions
    "density_loss_scaling", "dense_loss_thresh", "dense_loss_norm", "dense_loss_alpha", "dense_loss_max_boost",
    # RMR-v21 / RMR-v30 additions
    "elementwise_dense_scaling",
    "output_stride", "lambda_carrier_cell", "lambda_fine_cell",
    # Spectral Loss (H2/H8) & Regional Mass Weight (H8)
    "use_spectral_loss", "lambda_spectral", "spectral_beta", "lambda_spectral_dc",
    "spectral_omega_0", "spectral_bandpass", "spectral_omega_low", "spectral_omega_high",
    "spectral_transform", "regional_mass_weight_alpha", "regional_nb_beta", "faithful_regional_nb",
    # CI-Cell Loss & Count-Harmonized Cell Loss additions
    "cell_tau_head", "cell_alpha", "cell_fg_ratio", "cell_norm_power", "cell_norm_ref",
    # FIDT (H1) & ChfL (H2) additions
    "fidt_k", "fidt_loss_type", "fidt_loss_mode", "fidt_normalize_by_count",
    "use_chfl", "use_chfl_loss", "lambda_chfl", "chfl_canonical", "chfl_step", "chfl_tik", "chfl_bandwidth",
    "chfl_num_frequencies", "chfl_omega_max",
    # DM block resolution and concentration scaling
    "dm_block_px", "auto_scale_kappa",
    "dm_norm_mode", "dm_ref_count",
    # Orthogonal carrier-solver routing & Bayesian loss configuration
    "count_target", "cell_target", "bayesian_norm_mode", "bayesian_canonical_bg",
    "bayesian_adaptive_sigma", "adaptive_sigma", "bayesian_sigma_min", "bayesian_sigma_max",
    "lambda_bayesian", "strict_loss_triad",
}

ALLOWED_TRAIN_KEYS = {
    "batch_size", "workers", "pin_memory", "lr", "backbone_lr_scale", "weight_decay",
    "epochs", "warmup_epochs", "warmup_steps", "eval_every", "grad_clip", "amp", "early_stopping",
    "patience", "solver_warmup_epochs", "solver_ramp_epochs", "deterministic",
    "ema_decay", "min_lr_ratio", "grad_scaler_init_scale",
    "device", "num_threads", "cudnn_benchmark",
    # Optimizer & Scheduler additions (Gen 18 / Gen 22)
    "optimizer", "scheduler_type", "wsd_stable_ratio", "betas",
    "schedule_free_warmup_steps", "schedule_free_r", "schedule_free_weight_lr_power",
    "auto_lr_finder", "lr_finder_min_lr", "lr_finder_max_lr", "lr_finder_num_iter", "lr_finder_max_safe_lr",
    "prodigy_d_coef", "prodigy_growth_rate", "prodigy_d_max_cap", "prodigy_d_warmup_steps",
    "prodigy_grad_spike_thresh", "prodigy_use_rms_clipping", "prodigy_d0",
}

ALLOWED_EVAL_KEYS = {
    "density_bins",
}

SECTION_ALLOWED_KEYS = {
    "data": ALLOWED_DATA_KEYS,
    "model": ALLOWED_MODEL_KEYS,
    "loss": ALLOWED_LOSS_KEYS,
    "train": ALLOWED_TRAIN_KEYS,
    "eval": ALLOWED_EVAL_KEYS,
}

METHOD_CRITICAL_FIELDS: dict[str, list[str]] = {
    "model": [
        "output_stride",
        "feature_width",
        "backbone_name",
        "backbone",
        "region_sizes_px",
        "region_overlap",
        "include_full_image",
        "iterations",
        "omega",
        "sirt_omega",
        "residual_clip",
        "dispersion_init",
        "dispersion_min",
        "dispersion_max",
        "reliability_mode",
        "reliability_rate_std_floor",
        "reliability_weight_min",
        "reliability_weight_max",
        "normalize_reliability_within_scale",
        "detach_region_mean_in_solver",
        "detach_reliability_in_solver",
        "uniform_reliability",
        "eps",
        "native_scale_pooling",
        "regional_feature_stats",
        "region_head_hidden",
        "neck_type",
        "context_dilations",
        "use_aspp_gap",
        "aspp_dilations",
        "hurdle_head",
        "temp_softplus",
        "solver_mode",
        "density_gate_rho",
        "density_gate_floor",
        "tv_type",
        "tv_lambda",
        "tv_eps_c",
        "use_coord_attn",
        "proximal_tau",
        "proximal_mode",
        "proximal_mu",
        "dynamic_scale_routing",
        "scale_router_temperature",
        "trust_region_kappa",
        "trust_region_floor",
        "foreground_gate",
        "adjoint_mode",
        "morozov_gamma",
        "use_top_down_semantic_gate",
        "tdsg_floor",
        "fg_gate_floor",
        "scale_conditioned_prior",
        "pre_solver_scale_gating",
        "scale_gating_power",
        "dynamic_trust_gate",
        "trust_gate_init_bias",
        "density_curvature",
        "use_scale_entropy_trust",
        "perspective_scale_bias",
        "perspective_horizon_gate",
        "horizon_cutoff",
        "factorized_scale_routing",
        "num_marginal_scales",
        "num_aspect_ratios",
        "gated_density_curvature",
        "curvature_dense_threshold",
        "curvature_gate_beta",
        "curvature_pool_kernel",
        "use_micro_coord_attn",
        "micro_coord_reduction",
        "use_nesterov_momentum",
        "adaptive_relaxation",
        "adaptive_relax_sparse",
        "adaptive_relax_dense_boost",
        "adaptive_relax_threshold",
        "adaptive_relax_scale",
        "hybrid_recovery_alpha",
        "use_barzilai_borwein",
        "scale_conditioned_fine_head",
        "density_gated_diffusion",
        "diffusion_dense_threshold",
        "diffusion_gate_beta",
        "use_perspective_elevation",
        "use_alternating_bb",
        "bb_clamp_min",
        "bb_clamp_max",
        "cyclic_bb_length",
        "enable_solver",
        "init_m0",
        # RMR-v31/v32/v33 additions
        "anisotropic_diffusion", "pm_kappa", "density_gated_anscombe", "anscombe_tau_dense",
        "area_normalized_adjoint", "use_anscombe_sirt", "anscombe_c", "adaptive_tau", "adaptive_tau_rho0",
        "use_cpcm", "cpcm_hidden", "floor_tau",
        "resonant_adjoint", "resonant_adjoint_lambda", "anscombe_morozov",
        "crest_discovery_flux", "crest_kappa_0", "crest_eps_seed",
        "asymmetric_morozov", "morozov_gamma_under", "morozov_rho",
        "subpixel_stride2", "subpixel_dm", "curvature_alpha_init",
        "spatial_morozov", "morozov_gamma_scales", "scale_routed_trust",
        "scale_seeded_carrier", "scale_seed_eps", "detach_y0_for_solver",
        "trust_region_floor_dense",
        # PARK Perspective-Adaptive Regional Kernels
        "use_park", "park_mode", "park_horizon_h", "park_foreground_h",
        "park_max_aspect", "use_pgh", "park_routing", "park_altitude_bands",
    ],
    "loss": [
        "lambda_count", "lambda_flat_dm16", "lambda_cell", "lambda_region_nb", "lambda_hurdle", "lambda_trunc_nb",
        "count_loss_mode", "count_nb_dispersion", "kappa_flat16", "normalize_flat_dm16", "cell_beta",
        "use_hierarchical_dm", "use_multiscale_dm", "dm_block_sizes_px", "dm_weights", "dm_kappas",
        "cell_loss_mode", "cell_mass_weight_alpha", "cell_mass_weight_eps", "allocation_loss_type", "dm_target",
        "cell_mass_weight_gamma", "lambda_curvature", "lambda_hard_bg", "hard_bg_ratio", "lambda_fg_gate",
        "curvature_gate_threshold", "curvature_gate_kernel", "curvature_gate_mode", "curvature_gate_scale",
        "lambda_scale_align", "scale_align_tau_dense", "scale_align_tau_sparse", "scale_align_kernel",
        "scale_align_mask_bg", "density_loss_scaling", "elementwise_dense_scaling",
        "output_stride", "lambda_carrier_cell", "lambda_fine_cell",
        "spectral_transform", "use_spectral_loss", "lambda_spectral", "spectral_beta", "lambda_spectral_dc",
        "spectral_omega_0", "spectral_bandpass", "spectral_omega_low", "spectral_omega_high",
        "regional_mass_weight_alpha", "cell_tau_head", "cell_alpha",
        "dense_loss_thresh", "dense_loss_norm", "dense_loss_alpha", "dense_loss_max_boost",
        "bayesian_sigma", "bayesian_background_ratio", "ot_reg", "ot_num_iters", "dm_strict",
        "bayesian_norm_mode", "bayesian_adaptive_sigma", "adaptive_sigma",
    ],
    "train": [
        "lr",
        "backbone_lr_scale",
        "weight_decay",
        "epochs",
        "warmup_epochs",
        "batch_size",
        "deterministic",
        "solver_warmup_epochs",
        "solver_ramp_epochs",
        "workers",
        "eval_every",
        "early_stopping",
        "patience",
        "wsd_stable_ratio",
        "min_lr_ratio",
    ],
    "data": [
        "crop_size",
        "scale_range",
        "hflip_prob",
        "brightness_jitter",
        "contrast_jitter",
        "gamma_jitter",
        "random_invert_prob",
        "pad_small_images",
    ],
}

CRITICAL_TRAIN_DEFAULTS: dict[str, Any] = {
    "workers": 0,
    "eval_every": 5,
    "early_stopping": False,
    "patience": 0,
    "deterministic": True,
    "amp": True,
    "grad_clip": 1.0,
    "solver_warmup_epochs": 5,
    "solver_ramp_epochs": 5,
    "warmup_epochs": 5,
    "freeze_bn_after_epoch": -1,
    "wsd_stable_ratio": 0.75,
    "min_lr_ratio": 0.01,
}
